# Generated by Django 4.2.4 on 2023-08-21 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogapp', '0002_category_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
