# Generated by Django 4.2.4 on 2023-08-11 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0003_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tags', to='productapp.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='freeDelivery',
            field=models.BooleanField(default=False),
        ),
    ]
