# Generated by Django 4.2.4 on 2023-08-12 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0010_specification_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('id',)},
        ),
    ]
