# Generated by Django 4.2.4 on 2023-08-12 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0011_alter_product_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='product',
        ),
    ]
