# Generated by Django 4.2.4 on 2023-08-12 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0013_product_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
    ]
