# Generated by Django 4.2.4 on 2023-08-12 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0014_remove_product_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(null=True, related_name='product', to='productapp.tag'),
        ),
    ]
