# Generated by Django 4.2.4 on 2023-08-12 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0016_alter_product_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='salePrice',
            field=models.FloatField(null=True),
        ),
    ]
