# Generated by Django 4.2.4 on 2023-08-14 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0017_product_saleprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dateFrom',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='dateTo',
            field=models.DateField(blank=True, null=True),
        ),
    ]
