# Generated by Django 4.2.4 on 2023-08-17 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0021_product_sales_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sales_count',
            new_name='salesCount',
        ),
    ]
