# Generated by Django 4.2.4 on 2023-08-21 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0022_rename_sales_count_product_salescount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('id',), 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterModelOptions(
            name='specification',
            options={'verbose_name': 'Спецификация', 'verbose_name_plural': 'Спецификации'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Тэг', 'verbose_name_plural': 'Теги'},
        ),
    ]
