# Generated by Django 4.2.4 on 2023-08-22 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0025_alter_product_saleprice_alter_product_salescount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='product', to='productapp.tag'),
        ),
    ]
