# Generated by Django 4.2.4 on 2023-08-22 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0026_alter_product_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.CharField(default='Без имени', max_length=50),
        ),
    ]
