# Generated by Django 4.2.4 on 2023-08-06 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0003_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=11, null=True),
        ),
    ]
