# Generated by Django 4.2.4 on 2023-08-21 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0005_alter_profile_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
    ]
