# Generated by Django 4.2.4 on 2023-08-16 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0020_alter_product_rating'),
        ('orderapp', '0002_order_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(related_name='products', to='productapp.product'),
        ),
    ]
