# Generated by Django 4.2.4 on 2023-08-16 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0003_order_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deliveryType',
            field=models.CharField(default='free', max_length=30),
            preserve_default=False,
        ),
    ]
