# Generated by Django 4.2.4 on 2023-08-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0006_alter_order_address_alter_order_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paymentType',
            field=models.CharField(default='online', max_length=30),
        ),
    ]
