# Generated by Django 4.2.4 on 2023-08-16 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0005_alter_profile_phone'),
        ('orderapp', '0010_productorder_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profileapp.profile'),
            preserve_default=False,
        ),
    ]
