# Generated by Django 4.2.4 on 2023-08-16 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0012_productorder_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productorder',
            old_name='product',
            new_name='productId',
        ),
        migrations.RenameField(
            model_name='productorder',
            old_name='profile',
            new_name='profileId',
        ),
    ]
