# Generated by Django 4.2.4 on 2023-08-16 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0015_alter_productorder_orderid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('maxCost', models.PositiveIntegerField(null=True)),
                ('deliveryPrice', models.PositiveIntegerField()),
            ],
        ),
    ]
