# Generated by Django 4.2.4 on 2023-08-16 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0016_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='maxCost',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
