# Generated by Django 4.2.4 on 2023-08-22 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0019_alter_delivery_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
